<?php

namespace App\Filters;

use CodeIgniter\Filters\FilterInterface;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use App\Models\TvModel;

class TvPinSessionFilter implements FilterInterface
{
    public function before(RequestInterface $request, $arguments = null)
    {
        $uri = $request->getUri();
        // Segment 2 for /display/{slug}
        $slug = $uri->getSegment(2);

        if (!$slug) {
            return redirect()->to('/');
        }

        $tvModel = new TvModel();
        $tv = $tvModel->where('slug', $slug)->where('is_active', 1)->first();

        if (!$tv) {
            session()->setFlashdata('error', 'Display TV tidak ditemukan atau nonaktif.');
            return redirect()->to('/');
        }

        $tvId = (int) $tv['id'];
        $sessionKey = 'tv_verified_' . $tvId;
        $sessionData = session()->get($sessionKey);

        if (!$sessionData) {
            session()->setFlashdata('error', 'Silakan masukkan PIN 6-digit untuk mengakses TV ini.');
            return redirect()->to('/');
        }

        // Check if PIN was regenerated by admin after session verification
        if ($tv['pin_updated_at']) {
            $pinUpdatedAt = strtotime($tv['pin_updated_at']);
            $verifiedAt   = $sessionData['verified_at'] ?? 0;

            if ($pinUpdatedAt > $verifiedAt) {
                // PIN was updated! Invalidate session
                session()->remove($sessionKey);
                session()->setFlashdata('error', 'PIN untuk TV ini telah diperbarui oleh Admin. Silakan masukkan PIN baru.');
                return redirect()->to('/');
            }
        }
    }

    public function after(RequestInterface $request, ResponseInterface $response, $arguments = null)
    {
        // Do nothing
    }
}
